-- ChallengeGrind — English texts generated by the database
CREATE OR REPLACE FUNCTION public.set_user_ban(p_user_id uuid, p_banned boolean, p_reason text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  target public.app_role;
begin
  perform public.require_rank(3);
  if p_user_id = auth.uid() then raise exception 'cannot ban yourself'; end if;
  select role into target from public.profiles where id = p_user_id;
  if not found then raise exception 'user not found'; end if;
  if public.role_rank(target) >= public.my_rank() then
    raise exception 'insufficient permissions' using errcode = '42501';
  end if;

  update public.profiles
     set banned = p_banned,
         ban_reason = case when p_banned then nullif(trim(p_reason), '') else null end,
         role = case when p_banned then 'player'::public.app_role else role end
   where id = p_user_id;

  if p_banned then
    update public.records
       set status = 'rejected', reviewer_id = auth.uid(), reviewed_at = now(), review_note = 'Player banned'
     where player_id = p_user_id and status = 'pending';
    delete from auth.sessions where user_id = p_user_id;
  end if;
end $function$
;
